---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - namespaces
  - pods
  - serviceaccounts
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - oidcshim.kemo.dev
  resources:
  - clusteroidcshims
  - oidcshims
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - oidcshim.kemo.dev
  resources:
  - clusteroidcshims/status
  - oidcshims/status
  verbs:
  - get
  - patch
  - update
