## Append samples of your project ##
resources:
- oidcshim_v1alpha1_oidcshim_gcp.yaml
- oidcshim_v1alpha1_oidcshim_aws.yaml
- oidcshim_v1alpha1_clusteroidcshim_azure.yaml
- oidcshim_v1alpha1_clusteroidcshim_generic.yaml
# +kubebuilder:scaffold:manifestskustomizesamples
